import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
import { buildApp } from '../apps/api/src/app.js';

const app = buildApp({ NODE_ENV: 'test', HOST: '127.0.0.1', PORT: 0, DATABASE_URL: ':memory:', APP_ORIGIN: undefined, SESSION_SECRET: 'a'.repeat(32), AI_BASE_URL: 'http://127.0.0.1:1', AI_API_KEY: '', AI_MODEL: '', AI_TIMEOUT_MS: 100, DATA_ENCRYPTION_KEY: Buffer.alloc(32, 7).toString('base64'), AI_ALLOWED_HOSTS: undefined, LOG_LEVEL: 'silent', TRUST_PROXY: false });
await app.listen({ host: '127.0.0.1', port: 0 });
const address = app.server.address(); const origin = `http://127.0.0.1:${typeof address === 'object' && address ? address.port : 0}`;
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } }); await page.goto(origin); await page.getByRole('button', { name: /高中数学/ }).click(); await page.locator('.katex').first().waitFor();
  await page.getByRole('button', { name: '设置' }).click(); await page.locator('#ai-base-url').fill('http://127.0.0.1:9999/v1'); await page.locator('#ai-model').fill('browser-model'); await page.locator('#ai-key').fill('browser-only-secret'); await page.locator('#save-ai-config').click(); await page.getByText('已保存。密钥不会再次显示。').waitFor(); assert.equal(await page.locator('#ai-key').inputValue(), ''); assert.equal(await page.locator('body').textContent().then((text) => text?.includes('browser-only-secret')), false); assert.equal(await page.evaluate(() => `${localStorage.length}:${sessionStorage.length}`), '0:0'); page.once('dialog', (dialog) => dialog.accept()); await page.locator('#clear-ai-config').click(); await page.locator('#ai-settings-feedback').getByText('已清除，AI 功能目前未配置。').waitFor(); await page.locator('#close-modal').click();
  const selection = await page.evaluate(() => { const body = document.querySelectorAll<HTMLElement>('.message-text')[1]!; const text = body.dataset.source!, start = text.indexOf('平方项总是非负'), end = start + '平方项总是非负'.length; const leaf = [...body.querySelectorAll<HTMLElement>('[data-source-start]')].find((node) => Number(node.dataset.sourceStart) <= start && Number(node.dataset.sourceStart) + node.textContent!.length >= end)!; const range = document.createRange(); range.setStart(leaf.firstChild!, start - Number(leaf.dataset.sourceStart)); range.setEnd(leaf.firstChild!, end - Number(leaf.dataset.sourceStart)); const selected = window.getSelection()!; selected.removeAllRanges(); selected.addRange(range); body.dispatchEvent(new PointerEvent('pointerup', { bubbles: true })); return { start, end }; });
  await page.locator('#expand-selection').click(); await page.locator('#modal-body details').last().locator('summary').click(); await page.locator('[data-context-id]').first().uncheck(); await page.locator('#fork-prompt').fill('为什么配方以后能看见顶点？'); await page.locator('#modal-confirm').click(); await page.getByText(/模型尚未配置/).waitFor();
  assert.equal(await page.locator('.anchor .full-text').first().textContent(), '平方项总是非负'); assert.equal(await page.locator('.inherited-background .message').count(), 1);
  await page.getByRole('button', { name: '返回草稿编辑' }).click(); await page.locator('#draft').fill('结合我之前聊过的完全平方公式再解释'); await page.waitForTimeout(700); await page.locator('#send').click(); await page.locator('#history-gate').waitFor(); await page.getByText('选择并确认引用').click(); await page.locator('#source-select').selectOption({ label: '完全平方公式：为什么要补 4' }); await page.locator('#source-candidates input[type=checkbox]').first().check(); await page.locator('#modal-confirm').click(); await page.getByText(/模型尚未配置/).waitFor();
  await page.getByRole('button', { name: '管理' }).click(); await page.locator('#topic-title').fill('顶点笔记'); await page.locator('#topic-tags').fill('配方法, 二次函数'); await page.locator('#modal-confirm').click(); await page.locator('#tag-filter').selectOption('二次函数'); assert.ok(await page.locator('.branch-button').count() >= 1);
  await page.getByRole('button', { name: '返回原文' }).click(); await page.waitForFunction(() => window.getSelection()!.toString().length > 0); assert.equal(await page.evaluate(() => window.getSelection()!.toString()), '平方项总是非负');
  await page.locator('[data-switch]').filter({ hasText: '顶点笔记' }).click(); await page.getByRole('button', { name: '管理' }).click(); await page.getByRole('button', { name: '删除主题' }).click(); await page.locator('#modal-confirm').click(); await page.locator('#undo').click(); await page.reload(); await page.locator('.branch-button').filter({ hasText: '顶点笔记' }).waitFor();
  await page.screenshot({ path: 'test-results/browser-smoke.png', fullPage: true }); console.log(`PASS browser smoke: selection ${selection.start}-${selection.end}, branch/history/tags/return/delete-undo/server refresh/offline retry`);
} finally { await browser.close(); await app.close(); }
