import { useEffect, useState } from 'react';
import { api } from '../api.js';

export function ProviderSettings() {
  const [provider, setProvider] = useState('openai'), [baseUrl, setBase] = useState(''), [model, setModel] = useState(''), [key, setKey] = useState('');
  const [timeoutMs, setTimeout] = useState(60000), [maxTokens, setTokens] = useState(4096), [temperature, setTemperature] = useState(''), [feedback, setFeedback] = useState(''), [busy, setBusy] = useState(false), [ready, setReady] = useState(false);
  useEffect(() => { let live = true; void api.aiConfig().then(c => { if (!live) return; setProvider(c.provider ?? 'openai'); setBase(c.baseUrl ?? ''); setModel(c.model ?? ''); setTimeout(c.timeoutMs ?? 60000); setTokens(c.maxTokens ?? 4096); setTemperature(c.temperature == null ? '' : String(c.temperature)); setReady(true); }).catch(e => { if (live) setFeedback(e.message); }); return () => { live = false; }; }, []);
  const run = async (task: () => Promise<unknown>, message: string) => { setBusy(true); try { await task(); setKey(''); setFeedback(message); } catch (e) { setFeedback((e as Error).message); } finally { setBusy(false); } };
  return <section className="settings-section"><h3>模型连接</h3><form id="ai-settings" onSubmit={e => { e.preventDefault(); void run(() => api.saveAiConfig({ provider, baseUrl, model, apiKey: key, timeoutMs, maxTokens, temperature: temperature === '' ? null : Number(temperature) }), '已保存。密钥不会再次显示。'); }}>
    <fieldset disabled={!ready || busy}><label className="field">协议<select id="ai-provider" value={provider} onChange={e => setProvider(e.target.value)}><option value="openai">OpenAI compatible</option><option value="anthropic">Anthropic Messages</option><option value="gemini">Gemini</option></select></label>
    <label className="field">Base URL<input id="ai-base-url" type="url" required maxLength={2048} value={baseUrl} onChange={e => setBase(e.target.value)} /></label><label className="field">模型<input id="ai-model" required maxLength={200} value={model} onChange={e => setModel(e.target.value)} /></label><label className="field">API key（留空保留已有密钥）<input id="ai-key" type="password" autoComplete="new-password" maxLength={4096} value={key} onChange={e => setKey(e.target.value)} /></label>
    <details><summary>高级参数</summary><label className="field">超时（毫秒）<input id="ai-timeout" type="number" min={100} max={600000} value={timeoutMs} onChange={e => setTimeout(Number(e.target.value))} /></label><label className="field">最大输出 tokens<input type="number" min={1} max={65536} value={maxTokens} onChange={e => setTokens(Number(e.target.value))} /></label><label className="field">Temperature（可选）<input type="number" min={0} max={1} step={0.1} value={temperature} onChange={e => setTemperature(e.target.value)} /></label></details>
    <div className="toolbar"><button id="save-ai-config" type="submit" disabled={busy}>保存模型配置</button><button type="button" disabled={busy} onClick={() => void run(api.testAiConfig, '连接成功。')}>测试连接</button><button type="button" disabled={busy} onClick={() => void run(api.clearAiConfig, '已清除配置。')}>清除配置</button></div><p id="ai-settings-feedback" role="status">{feedback}</p>
    </fieldset></form></section>;
}
