import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';
import { lookup } from 'node:dns/promises';
import { isIP } from 'node:net';
import type { Config } from '../config.js';
import type { SqliteDatabase } from '../db/client.js';
import { ApiError } from './ai.js';

type Row = { user_id: string; version: number; base_url: string; model: string; timeout_ms: number; encrypted_key: string; nonce: string; auth_tag: string; updated_at: string };
export type PublicAiConfig = { configured: boolean; baseUrl: string | null; model: string | null; timeoutMs: number | null; updatedAt: string | null; source: 'user' | 'environment' | 'none' };
export type ResolvedAiConfig = { baseUrl: string; model: string; apiKey: string; timeoutMs: number };

let developmentKey: Buffer | undefined;
function encryptionKey(config: Config): Buffer | undefined {
  if (config.DATA_ENCRYPTION_KEY) { const key = Buffer.from(config.DATA_ENCRYPTION_KEY, 'base64'); if (key.length !== 32) throw new Error('DATA_ENCRYPTION_KEY 必须是 32-byte base64 密钥。'); return key; }
  if ((config.APP_ENV ?? config.NODE_ENV) === 'production') return undefined;
  developmentKey ??= randomBytes(32);
  return developmentKey;
}
function privateAddress(address: string) { const normalized = address.toLowerCase(); if (normalized === '::' || normalized === '::1' || normalized.startsWith('::ffff:') || normalized.startsWith('fe80:') || normalized.startsWith('fc') || normalized.startsWith('fd')) return true; if (isIP(address) !== 4) return false; const [a, b] = address.split('.').map(Number); return a === 0 || a === 10 || a === 127 || (a === 100 && b >= 64 && b <= 127) || (a === 169 && b === 254) || (a === 172 && b >= 16 && b <= 31) || (a === 192 && b === 168); }

export class UserAiConfigService {
  private readonly key: Buffer | undefined;
  private readonly allowedHosts: Set<string>;
  constructor(private readonly sqlite: SqliteDatabase, private readonly config: Config, log: { warn: (obj: object, message: string) => void }) { this.key = encryptionKey(config); this.allowedHosts = new Set((config.AI_ALLOWED_HOSTS ?? '').split(',').map((host) => host.trim().toLowerCase()).filter(Boolean)); if (!config.DATA_ENCRYPTION_KEY && (config.APP_ENV ?? config.NODE_ENV) === 'development') log.warn({}, 'DATA_ENCRYPTION_KEY is unset: generated an ephemeral key; saved model credentials cannot survive a restart'); }
  private aad(userId: string, version: number) { return Buffer.from(`${userId}:${version}`); }
  private row(userId: string) { return this.sqlite.prepare('SELECT * FROM user_ai_configs WHERE user_id=?').get(userId) as Row | undefined; }
  private async validateUrl(value: string) { const environment = this.config.APP_ENV ?? this.config.NODE_ENV; let url: URL; try { url = new URL(value); } catch { throw new ApiError(400, '模型地址必须是绝对 HTTP(S) URL。'); } if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password) throw new ApiError(400, '模型地址必须是不含凭据的绝对 HTTP(S) URL。'); if (environment === 'production' && url.protocol !== 'https:') throw new ApiError(400, '生产环境仅允许 HTTPS 模型地址。'); const host = url.hostname.toLowerCase(); if (this.allowedHosts.size && !this.allowedHosts.has(host)) throw new ApiError(400, '模型地址不在 AI_ALLOWED_HOSTS 允许列表中。'); const addresses = isIP(host) ? [{ address: host }] : await lookup(host, { all: true, verbatim: true }).catch(() => { throw new ApiError(400, '模型地址的主机名无法解析。'); }); if (!addresses.length || addresses.some(({ address }) => privateAddress(address))) { const localDevelopment = environment !== 'production' && addresses.length > 0 && addresses.every(({ address }) => address === '127.0.0.1' || address === '::1'); if (!localDevelopment) throw new ApiError(400, '模型地址不能指向本机、私有或链路本地网络。'); } return url.toString().replace(/\/$/, ''); }
  async save(userId: string, input: { baseUrl: string; model: string; apiKey: string; timeoutMs?: number }) { if (!this.key) throw new ApiError(503, '生产环境未配置 DATA_ENCRYPTION_KEY，无法保存模型密钥。'); const previous = this.row(userId); if (!input.apiKey && !previous) throw new ApiError(400, '首次保存模型配置时必须提供 API key。'); const version = (previous?.version ?? 0) + 1, apiKey = input.apiKey || this.decrypt(previous!), nonce = randomBytes(12); const cipher = createCipheriv('aes-256-gcm', this.key, nonce); cipher.setAAD(this.aad(userId, version)); const encrypted = Buffer.concat([cipher.update(apiKey, 'utf8'), cipher.final()]); const now = new Date().toISOString(), baseUrl = await this.validateUrl(input.baseUrl); this.sqlite.prepare('INSERT INTO user_ai_configs (user_id,version,base_url,model,timeout_ms,encrypted_key,nonce,auth_tag,updated_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET version=excluded.version,base_url=excluded.base_url,model=excluded.model,timeout_ms=excluded.timeout_ms,encrypted_key=excluded.encrypted_key,nonce=excluded.nonce,auth_tag=excluded.auth_tag,updated_at=excluded.updated_at').run(userId, version, baseUrl, input.model.trim(), input.timeoutMs ?? this.config.AI_TIMEOUT_MS, encrypted.toString('base64'), nonce.toString('base64'), cipher.getAuthTag().toString('base64'), now); return this.public(userId); }
  clear(userId: string) { this.sqlite.prepare('DELETE FROM user_ai_configs WHERE user_id=?').run(userId); return this.public(userId); }
  public(userId: string): PublicAiConfig { const row = this.row(userId); if (row) return { configured: true, baseUrl: row.base_url, model: row.model, timeoutMs: row.timeout_ms, updatedAt: row.updated_at, source: 'user' }; if (this.config.AI_API_KEY && this.config.AI_MODEL) return { configured: true, baseUrl: this.config.AI_BASE_URL, model: this.config.AI_MODEL, timeoutMs: this.config.AI_TIMEOUT_MS, updatedAt: null, source: 'environment' }; return { configured: false, baseUrl: null, model: null, timeoutMs: null, updatedAt: null, source: 'none' }; }
  private decrypt(row: Row) { if (!this.key) throw new ApiError(503, '生产环境未配置 DATA_ENCRYPTION_KEY，无法读取已保存的模型密钥。'); try { const decipher = createDecipheriv('aes-256-gcm', this.key, Buffer.from(row.nonce, 'base64')); decipher.setAAD(this.aad(row.user_id, row.version)); decipher.setAuthTag(Buffer.from(row.auth_tag, 'base64')); return Buffer.concat([decipher.update(Buffer.from(row.encrypted_key, 'base64')), decipher.final()]).toString('utf8'); } catch { throw new ApiError(503, '已保存的模型密钥无法解密，请重新配置。'); } }
  async resolve(userId: string): Promise<ResolvedAiConfig | undefined> { const row = this.row(userId); if (row) return { baseUrl: await this.validateUrl(row.base_url), model: row.model, apiKey: this.decrypt(row), timeoutMs: row.timeout_ms }; if (this.config.AI_API_KEY && this.config.AI_MODEL) return { baseUrl: await this.validateUrl(this.config.AI_BASE_URL), model: this.config.AI_MODEL, apiKey: this.config.AI_API_KEY, timeoutMs: this.config.AI_TIMEOUT_MS }; return undefined; }
}
