import Fastify from 'fastify'; import cors from '@fastify/cors'; import helmet from '@fastify/helmet'; import rateLimit from '@fastify/rate-limit'; import fastifyStatic from '@fastify/static'; import { randomUUID } from 'node:crypto'; import { resolve } from 'node:path'; import { ZodError } from 'zod'; import { actionSchema, aiConfigSchema, chatSchema, importSchema, metadataSchema, rerankSchema, restoreSchema } from '@zhijing/contracts'; import { branchOf, transition, validateState } from '@zhijing/domain'; import { loadConfig, type Config } from './config.js'; import { openDatabase } from './db/client.js'; import { WorkspaceRepository, WorkspaceConflictError } from './repositories/workspace.js'; import { LocalAuthService } from './services/auth.js'; import { AiGateway, ApiError } from './services/ai.js'; import { UserAiConfigService } from './services/ai-config.js';
export function buildApp(config: Config = loadConfig()) {
  const app = Fastify({ logger: { level: config.LOG_LEVEL, base: undefined }, genReqId: () => randomUUID(), bodyLimit: 1_000_000, trustProxy: config.TRUST_PROXY }); const { sqlite } = openDatabase(config.DATABASE_URL); const repository = new WorkspaceRepository(sqlite); const auth = new LocalAuthService(sqlite, config.NODE_ENV === 'production'); const userAiConfigs = new UserAiConfigService(sqlite, config, app.log); const ai = new AiGateway(config, userAiConfigs);
  app.decorateRequest('userId', ''); app.addHook('onRequest', async (request, reply) => { request.userId = auth.requireUser(request, reply); }); app.addHook('onClose', async () => sqlite.close());
  void app.register(helmet, { contentSecurityPolicy: false }); void app.register(cors, { origin: config.APP_ORIGIN ?? false, credentials: true }); void app.register(rateLimit, { global: false }); void app.register(fastifyStatic, { root: resolve(process.cwd(), 'apps/web/dist'), prefix: '/', wildcard: false });
  app.setErrorHandler((error, request, reply) => { const candidate = error as { statusCode?: unknown }; const status = error instanceof ApiError ? error.status : error instanceof WorkspaceConflictError ? 409 : error instanceof ZodError ? 400 : typeof candidate.statusCode === 'number' ? candidate.statusCode : 500; request.log.warn({ err: error, status }, 'request failed'); reply.code(status).send({ error: error instanceof ApiError ? error.message : error instanceof WorkspaceConflictError ? '工作区已被其他请求更新，请刷新后重试。' : error instanceof ZodError ? '请求格式错误。' : '服务暂不可用。', requestId: request.id }); });
  app.get('/healthz', async () => ({ status: 'ok' })); app.get('/readyz', async () => { sqlite.prepare('SELECT 1').get(); return { status: 'ready', storage: 'sqlite-single-instance' }; }); app.get('/api/status', async (request) => { const current = userAiConfigs.public(request.userId); return { configured: current.configured, model: current.model, mode: current.configured ? 'configured' : 'offline' }; });
  app.get('/api/ai/config', async (request) => userAiConfigs.public(request.userId)); app.post('/api/ai/config', async (request) => userAiConfigs.save(request.userId, aiConfigSchema.parse(request.body))); app.post('/api/ai/config/clear', async (request) => { if ((request.body as { confirm?: unknown } | undefined)?.confirm !== true) throw new ApiError(400, '请确认清除模型配置。'); return userAiConfigs.clear(request.userId); }); app.post('/api/ai/config/test', { config: { rateLimit: { max: 5, timeWindow: '1 minute' } } }, async (request) => { await ai.connectTest(request.userId, request.signal); return { ok: true }; });
  app.get('/api/workspace', async (request) => repository.get(request.userId)); app.post('/api/workspace/actions', async (request) => { const action = actionSchema.parse(request.body); const current = repository.get(request.userId); const next = transition(current.state, action); const revision = repository.replace(request.userId, next, action.revision); return { state: next, revision }; }); app.post('/api/workspace/restore', async (request) => { const input = restoreSchema.parse(request.body); const state = validateState(input.state); const revision = repository.replace(request.userId, state, input.revision); return { state, revision }; }); app.get('/api/export', async (request) => ({ schemaVersion: 2, state: repository.get(request.userId).state })); app.post('/api/import', async (request) => { const input = importSchema.parse(request.body); let state; try { state = validateState(input.state); } catch { throw new ApiError(400, '导入的工作区数据损坏。'); } const revision = repository.replace(request.userId, state, input.revision); return { state, revision }; });
  app.post('/api/ai/chat', { config: { rateLimit: { max: 20, timeWindow: '1 minute' } } }, async (request) => { const { branchId, revision } = chatSchema.parse(request.body); const current = repository.get(request.userId); if (current.revision !== revision) throw new WorkspaceConflictError(); const branch = branchOf(current.state, branchId); if (!branch.awaiting || branch.entries.at(-1)?.role !== 'user') throw new ApiError(409, '没有等待回答的问题。'); const answer = await ai.chat(request.userId, { prompt: branch.entries.at(-1)!.text, anchor: branch.selection ? { text: branch.selection.text } : null, context: branch.entries.slice(0, -1).map((e) => ({ role: e.role, text: e.text })) }, request.signal); const next = transition(current.state, { type: 'answer', branchId, text: answer }); const nextRevision = repository.replace(request.userId, next, revision); return { state: next, revision: nextRevision, answer }; });
  app.post('/api/ai/metadata', { config: { rateLimit: { max: 20, timeWindow: '1 minute' } } }, async (request) => { const input = metadataSchema.parse(request.body); return ai.metadata(request.userId, input.prompt, input.answer, input.labels, request.signal); }); app.post('/api/ai/rerank', { config: { rateLimit: { max: 20, timeWindow: '1 minute' } } }, async (request) => ai.rerank(request.userId, ...Object.values(rerankSchema.parse(request.body)) as [string, { id: string; title: string; summary: string }[]], request.signal));
  return app;
}
declare module 'fastify' { interface FastifyRequest { userId: string } }
